### ISSUE TITLE
Algunos problemas con el archivo paquetes.tex

### ISSUE THREAD

**Issue by AACC1088** [ljtc/tesisFC#1]
Buen día profesor espero que se encuentre bien.
Le comento que el archivo paquetes.tex del repositorio tesisFC tiene un problema entre los renglones 
55-62, ya que aparece el signo "¡". Lo cual al principio me genero un error de compilación que se solucionó al eliminar dicho caracter. Saludos.

**Comment by ljtc** [comment]
Hola,
El comando \verb necesita un caracter para abrir y cerrar el modo verbatim. Además el símbolo que se usa con los fines anteriores no debe ser usado dentro del contenido que se pondrá en verbatim. En esas líneas estoy tratando de poner "|x|" en modo verbatim, por lo cual no puedo usar la barra para entrar y salir del modo verbatim, como en los casos anteriores. En mi computadora compila sin erroes, entonces algunas preguntas:
¿cuando quitaste los símbolos "¡" aún aparece |x| (con la barras) en modo verbatim o sólo "x"?
¿Si en lugar de de "¡" usas otro símbolo, digamos "+" o "*", sigue teniendo erroes al compilar?
¿Qué método de compilación usaste (pdflatex, lualatex)?
¿Qué error te mando cuando estaban los símbolos "¡"?

**Comment by AACC1088** [comment]
Buenas tardes profesor.
1-Cuando quito los símbolos "¡" aún aparece |x| (con las barras) en modo verbatim.
2-Cuando intercambio las apariciones de "¡" por el símbolo "+",  ya no me genera error al compilar.
3-El método de compilación que uso es lualatex.
4-El error que me aparece cuando están los símbolos "¡" es el siguiente:
paquetes.tex|55 error| LaTeX Error: Invalid UTF-8 byte "A1.

Gracias por responder, saludos.

**Comment by ljtc** [comment]
Parece que es un error de codificación de caracteres. Creo que lo mejor es evitar que vuelva a ocurrir, así que pondré un símbolo "estándar" como "+".
Gracias por usar la clase, por señalar el problema y por confirmar que no persiste después de usar otro símbolo
